site_name: Manual de Mobilitat
repo_url: https://github.com/yaknostoyok/mobilitat-manual
docs_dir: docs
theme: readthedocs

nav:
  - Inici: index.md
  - Gestió de mobilitat: 
    - Conceptes fonamentals: gestio/gestio-conceptes.md
    - Documents de mobilitat: gestio/gestio-docs.md
  - Referències:
    - Links d'interès: refs/refs-links.md

markdown_extensions:
  - admonition